name: quickbites_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  go_router: ^15.0.0
  crclib: ^3.0.0
  intl: ^0.20.2
  get: ^4.7.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/QuickBites_Logo.png
    - assets/google.png
